### ISSUE TITLE
SendAddonMessage not working correctly

### ISSUE THREAD

**Issue by iThorgrim** [ElunaLuaEngine/ElunaCataPreservation#2]
**Description:**
The SendAddonMessage method does not work correctly. It does not take into consideration the addon's "Prefix".

**Current behaviour:**
When you use : player:SendAddonMessage( prefix, message, channel, receiver ), prefix is not take in consideration.

**Steps to reproduce the problem:**

1. Just use player:SendAddonMessage

**TC rev. hash/commit:** 

TrinityCore rev. 9596c357ef8d+ 2023-11-05 18:50:54 -0600 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready...

**TDB version:**  TDB 434.22011

**Operating system:** Ubuntu 22.04

**Comment by Niam5** [comment]
This is more of how eluna handles the packets. If you have some way to test this apply this code over the existing and test.

In src\server\game\LuaEngine\TrinityCore\PlayerMethods.h line 3300 delete the entire function for SendAddonMessage and replace it with this

int SendAddonMessage(lua_State* L, Player* player)
{
    std::string prefix = Eluna::CHECKVAL<std::string>(L, 2);
    std::string message = Eluna::CHECKVAL<std::string>(L, 3);
    uint8 channel = Eluna::CHECKVAL<uint8>(L, 4);
    Player* receiver = Eluna::CHECKOBJ<Player>(L, 5);

    std::string fullmsg = prefix + "\t" + message;

    WorldPacket data(SMSG_MESSAGECHAT, 100);
    data << uint8(channel);
    data << int32(LANG_ADDON);
    data << player->GET_GUID();
    data << uint32(0);
    data << receiver->GET_GUID();
    data << prefix;
    data << uint32(message.length() + 1);
    data << message;
    data << uint8(0);

    receiver->GetSession()->SendPacket(&data);
    return 0;
}

**Comment by Rochet2** [comment]
Fixed here https://github.com/ElunaLuaEngine/Eluna/commit/ed947df40b51aade85598c29a413e7660c9b2727
The submodule still needs updating in this repo though.
